name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Update setiap 12 jam
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch WakaTime Data
        run: |
          curl -s 'https://wakatime.com/share/@Alhikam/4a6ef383-1135-4cf7-b84e-ee891402e27a.json' > waka-stats.json

      - name: Update README
        run: |
          echo '## â³ WakaTime Stats' > waka-output.md
          cat waka-stats.json | jq -r '.data[] | "* \(.name): \(.percent)%"' >> waka-output.md
          sed -i '/<!--START_WAKA-->/, /<!--END_WAKA-->/c\<!--START_WAKA-->\n'$(cat waka-output.md)'\n<!--END_WAKA-->' README.md

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update WakaTime stats"
          git push
